# Generated by Django 4.2.11 on 2024-05-26 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lycee', '0002_cursus_student_birth_date_student_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('acheteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acheteur', to='lycee.enseignant')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lycee.budget')),
                ('possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possesseur', to='lycee.enseignant')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='lycee.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Passation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('objectif_utilisation', models.TextField()),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.materiel')),
                ('possesseur_nouveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possesseur_nouveau', to='lycee.enseignant')),
                ('possesseur_precedent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possesseur_precedent', to='lycee.enseignant')),
            ],
        ),
    ]
