# Generated by Django 4.2.11 on 2024-05-26 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_budget_enseignant_materiel_passation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
                ('objectif_utilisation', models.CharField(max_length=255)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='lycee.materiel')),
                ('possesseur_nouveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_recus', to='lycee.enseignant')),
                ('possesseur_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_realises', to='lycee.enseignant')),
            ],
        ),
    ]
