# Generated by Django 4.2.11 on 2024-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='budget',
            field=models.CharField(default='', max_length=100),
        ),
    ]
